site_name: Isaac-HPC Tutorial
site_url: https://cold-young.github.io/Isaac-HPC/
repo_url: https://github.com/cold-young/Isaac-HPC
edit_uri: edit/main/docs/

theme:
  name: material  # material 테마로 변경
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

nav:
  - Home: index.md
  - 'Neuron (GPU)':
    - 'Overview': Neuron_KISTI/README.md
    - 'Build Environment': Neuron_KISTI/build_your_env.md
    - 'Job Examples': Neuron_KISTI/Exmaple_schedule.md
  - 'Nurion (CPU)':
    - 'Overview': Nurion_KISTI/README.md
    - 'Overall Guide': Nurion_KISTI/01_HPC_overall_guide.md
    - 'Job Tutorial': Nurion_KISTI/02_HPC_job_tutorial.md
    - 'PaScaL_TDMA Env': Nurion_KISTI/03_PaScaL_TDMA_env.md
    - 'SuperLU Dist': Nurion_KISTI/04_SuperLU_dist.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:  # arithmatex 앞에 pymdownx. 를 추가합니다.
      generic: true
  
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js